def VERSION = '0.11.0'
group 'io.github.tronprotocol'
def JITPACK_GROUP = "com.github.0xbigapple"

buildscript {
    repositories {
        mavenLocal()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
        }
        maven { url 'https://repo.spring.io/plugins-release' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "io.github.gradle-nexus:publish-plugin:1.1.0"
        classpath 'com.github.jengelman.gradle.plugins:shadow:5.2.0'
    }
}

apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'maven-publish'

ext {
    bouncycastleVersion = '1.78.1'
    junitJupiterVersion = '5.4.2'
    googleGuavaVersion = '33.0.0-jre'
}

allprojects {
    version = VERSION

    repositories {
        mavenCentral()
    }


    tasks.withType(Javadoc).tap {
        configureEach {
            options.encoding = 'UTF-8'
            options.charSet = 'UTF-8'
            options.addStringOption('Xdoclint:none', '-quiet')

            options {
                tags = [
                        'apiNote:a:API Note:',
                        'implSpec:a:Implementation Requirements:',
                        'implNote:a:Implementation Note:'
                ]
            }

            exclude '**/internal/**'
            exclude '**/impl/**'
            failOnError = false

            logging.captureStandardError LogLevel.INFO
            logging.captureStandardOutput LogLevel.INFO
        }
    }

    configurations.configureEach {
        resolutionStrategy {
            force "com.google.guava:guava:$googleGuavaVersion"
        }
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'

    tasks.withType(Jar).configureEach {
        destinationDirectory = rootProject.file("build/libs")
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    dependencies {
        testImplementation "org.junit.jupiter:junit-jupiter:$junitJupiterVersion"

        compileOnly 'org.projectlombok:lombok:1.18.12'
        annotationProcessor 'org.projectlombok:lombok:1.18.12'
        testCompileOnly 'org.projectlombok:lombok:1.18.12'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.12'
    }

    test {
        useJUnitPlatform()
        testLogging {
            events 'passed', 'skipped', 'failed'
        }
    }

    tasks.register('sourcesJar', Jar) {
        dependsOn classes
        classifier = 'sources'
        from sourceSets.main.allSource
    }

    tasks.register('javadocJar', Jar) {
        dependsOn javadoc
        classifier = 'javadoc'
        from javadoc.destinationDir
    }

    tasks.withType(JavaCompile).configureEach {
        //options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }

    artifacts {
        archives jar
    }

    configurations {
        checkstyleConfig
    }
    configurations.named('checkstyleConfig') {
        transitive = false
    }
    checkstyle {
        toolVersion = "8.29"
        configFile = file("../config/checkstyle/checkStyleAll.xml")
    }
    checkstyleMain {
        source = 'src/main/java'
        exclude '**/trident/api/**'
        exclude '**/trident/proto/**'
    }
    checkstyleTest {
        source = files() //use empty files to ignore test class
    }

    publishing {
        publications {
            "${project.name}Publication"(MavenPublication) {
                from components.java
                groupId = JITPACK_GROUP
                artifactId = "trident-${project.name}"
                version = VERSION
            }
        }
    }

}

shadowJar {
    zip64 = true
}

javadoc {
    source subprojects.collect { project ->
        project.sourceSets.main.allJava
    }
    classpath = files(subprojects.collect { project ->
        project.sourceSets.main.compileClasspath
    })
}

tasks.register('javadocJar', Jar) {
    archiveClassifier = 'javadoc'
    archiveVersion = VERSION
    from javadoc
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    archiveVersion = VERSION
    from subprojects.collect { project ->
        project.sourceSets.main.allSource
    }
}

tasks.register('buildLib', Jar) {
    archiveVersion = VERSION
    from subprojects.collect { project ->
        project.sourceSets.main.output
    }
}

tasks.named('build') {
    dependsOn javadocJar, sourcesJar, buildLib
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

// Root project publishing configuration
publishing {
    publications {
        tridentPublication(MavenPublication) {
            groupId = JITPACK_GROUP
            artifactId = 'trident'
            version = VERSION
            
            // Use the buildLib jar as the main artifact
            artifact buildLib
            
            // Add sources and javadoc
            artifact sourcesJar
            artifact javadocJar
            
            // Add dependencies from all subprojects
            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')
                subprojects.each { subproject ->
                    subproject.configurations.implementation.allDependencies.each { dep ->
                        if (dep.group && dep.name && dep.version) {
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('groupId', dep.group)
                            dependencyNode.appendNode('artifactId', dep.name)
                            dependencyNode.appendNode('version', dep.version)
                            dependencyNode.appendNode('scope', 'compile')
                        }
                    }
                }
            }
        }
    }
}