name: Dependency Check

on:
  push:
    branches: 
      - main
      - 'feature/dependency_check'
      - 'release/**'
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Download upload-artifact action
      - name: Download upload-artifact action
        uses: actions/download-artifact@v3
          
      # Install Dependency Check CLI
      - name: Setup Dependency-Check
        run: |
          mkdir -p $HOME/OWASP
          wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip -q dependency-check-6.5.3-release.zip -d $HOME/OWASP
          
      # Run Dependency Check
      - name: Run Dependency-Check
        run: |
          $HOME/OWASP/dependency-check/bin/dependency-check.sh \
            --scan . \
            --format "HTML" "JSON" \
            --out "build/reports" \
            --failOnCVSS 11 \
            --javaVersion "1.8" \
            --disableNodeAudit \
            --disableRubygems \
            --disablePyDist \
            --disablePyPkg \
            --disableComposer

      # Upload analysis results
      - name: Upload Dependency Check Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: build/reports/
          retention-days: 30