name: OWASP Dependency Check

on:
  push:
    branches:
      - main
      - 'release_**'
  workflow_dispatch:

jobs:
  scan:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Gradle build
        run: |
          ./gradlew build  -x test
      
      - name: Download Dependency Check CLI
        run: |
          VERSION=6.5.3
          wget -q "https://github.com/jeremylong/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip"
          unzip -q dependency-check-${VERSION}-release.zip
          chmod +x dependency-check/bin/dependency-check.sh
      
      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --scan build/libs \
            --scan ~/.gradle/caches/modules-2/files-2.1 \
            --format "HTML" \
            --format "JSON" \
            --out . \
            --failOnCVSS 11 \
            --project "trident" \
            --enableRetired \
            --disableAssembly \
            --disableNuspec \
            --disableNugetconf \
            --disableCentral \
            --disableOssIndex \
            --disableRetireJS

      - name: Count Vulnerability Severity Levels
        run: |
          # Count severity levels from HTML table
          CRITICAL=$(grep -o '<td data-sort-value="[0-9.]\+">CRITICAL</td>' dependency-check-report.html | wc -l)
          HIGH=$(grep -o '<td data-sort-value="[0-9.]\+">HIGH</td>' dependency-check-report.html | wc -l)
          MEDIUM=$(grep -o '<td data-sort-value="[0-9.]\+">MEDIUM</td>' dependency-check-report.html | wc -l)
          LOW=$(grep -o '<td data-sort-value="[0-9.]\+">LOW</td>' dependency-check-report.html | wc -l)

          # Display in workflow logs
          echo "::group::Vulnerability Severity Statistics"
          echo "CRITICAL: $CRITICAL"
          echo "HIGH: $HIGH"
          echo "MEDIUM: $MEDIUM"
          echo "LOW: $LOW"
          echo "TOTAL: $((CRITICAL + HIGH + MEDIUM + LOW))"
          echo "::endgroup::"

          # Add to Job Summary
          echo "### Dependency Security Scan Results :shield:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| :red_circle: CRITICAL | $CRITICAL |" >> $GITHUB_STEP_SUMMARY
          echo "| :orange_circle: HIGH | $HIGH |" >> $GITHUB_STEP_SUMMARY
          echo "| :yellow_circle: MEDIUM | $MEDIUM |" >> $GITHUB_STEP_SUMMARY
          echo "| :green_circle: LOW | $LOW |" >> $GITHUB_STEP_SUMMARY
          echo "| **TOTAL** | **$((CRITICAL + HIGH + MEDIUM + LOW))** |" >> $GITHUB_STEP_SUMMARY

      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: |
            dependency-check-report.html
            dependency-check-report.json
          retention-days: 30