name: OWASP Dependency Check

on:
  push:
    branches:
      - main
      - 'feature/dependency_check'
      - 'release/**'
  workflow_dispatch:

jobs:
  scan:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Download Dependency Check CLI
        run: |
          VERSION=6.5.3
          wget -q "https://github.com/jeremylong/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip"
          unzip -q dependency-check-${VERSION}-release.zip
          chmod +x dependency-check/bin/dependency-check.sh
      
      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --scan . \
            --format "HTML" "JSON" \
            --out . \
            --failOnCVSS 11 \
            --enableRetired \
            --disableAssembly \
            --disableNuspec \
            --disableNugetconf \
            --disableCentral \
            --disableOssIndex \
            --disableRetireJS

      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: |
            dependency-check-report.html
            dependency-check-report.json
          retention-days: 30